### PR TITLE
Making pool options configurable

### PR DESCRIPTION
**Pull request by wk8**
Fixes https://github.com/ErlyORM/boss_db/issues/181

Updated the README.

### CODE REVIEW

**Comment by wk8** [comment]
https://github.com/ErlyORM/boss_db/pull/182 is 3 years old, and seems to include other changes that are not relevant to that particular issue :)

**Comment by wk8** [comment]
Ping? :)

**Comment by danikp** [comment]
@wk8 , I will check it later today

**Comment by danikp** [comment]
merged, thanks

**Pull request merged**
